---
abstract: 'Mapping Perl releases on CPAN to the location of the tarballs'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Perl-Releases
requires:
  perl: v5.6.0
resources:
  homepage: https://github.com/bingos/cpan-perl-releases
  repository: https://github.com/bingos/cpan-perl-releases.git
version: 1.38
